version: '3.8'

services:
  api-nest:
    build:
      context: ./api-inbev 
      dockerfile: Dockerfile
    networks:
      - minha-rede
    ports:
      - "3000:3000" 
    depends_on:
      - ocr-service
      - mongo 
    volumes:
      - ./api-inbev:/app 
    environment:
      - MONGODB_URI=mongodb://mongo:27017/inbev 

  
  ocr-service:
    build:
      context: ./api-python 
      dockerfile: Dockerfile
    networks:
      - minha-rede
    ports:
      - "3001:3001" 
    volumes:
      - ./api-python:/app 

  
  
  mongo:
    image: mongo:6.0 
    networks:
      - minha-rede
    volumes:
      - ./api-nest/db
    ports:
      - "27017:27017" 

networks:
  minha-rede:
    driver: bridge

volumes:
  mongo_data:
