version: '3.8'

services:
  # Serviço do Nest.js
  api-nest:
    build:
      context: ./api-inbev # Caminho ajustado para o microsserviço em Nest.js
      dockerfile: Dockerfile
    networks:
      - minha-rede
    ports:
      - "3000:3000" # Mapeia a porta 3000 do container para a máquina host
    depends_on:
      - ocr-service
      - mongo # Garante que o MongoDB estará pronto antes de iniciar o Nest.js
    volumes:
      - ./api-inbev:/app # Sincroniza o código local com o container
    environment:
      - MONGO_URL=mongodb://mongo:27017/beerdb # Variável de conexão com o MongoDB

  # Serviço de OCR em Python
  ocr-service:
    build:
      context: ./api-python # Caminho ajustado para o microsserviço de OCR
      dockerfile: Dockerfile
    networks:
      - minha-rede
    ports:
      - "3001:3001" # Mapeia a porta 5000 do container para a máquina host
    volumes:
      - ./api-python:/app # Sincroniza o código local com o container

  # Serviço de banco de dados MongoDB
  mongo:
    image: mongo:6.0 # Usa a imagem oficial do MongoDB
    networks:
      - minha-rede
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017" # Exponha a porta padrão do MongoDB

networks:
  minha-rede:
    driver: bridge

volumes:
  mongo_data:
